name: inquiry
description: Sollywood inquiry application


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"



dependencies:
  flutter:
    sdk: flutter


  firebase_auth: ^3.3.5
  firebase_core: ^1.11.0
  firebase_messaging: ^11.2.5
  firebase_storage: ^10.2.5
  cloud_firestore: ^3.1.6
  image_cropper: ^1.4.1
  image_picker: ^0.8.1+3
  fluttertoast: ^8.0.7
  file_picker: ^4.3.2
  flutter_image_compress: ^1.0.0
  path_provider: ^2.0.2
  url_launcher: ^6.0.9
  geolocator: ^7.0.3
  geocoding: ^2.0.2
  shared_preferences: ^2.0.13

  flutter_icons:
    git:
      url: https://github.com/adarsh-technocrat/flutter-icons

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.2

  flutter_lints: ^1.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "images/icon.png"

flutter:


  uses-material-design: true


  assets:
  - images/icon.png
  - images/user.png
  - images/user.jpg
  - images/image.png
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # sollywood:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
